export const LIFTDLE_SPLASHLINES = [
  "Finally, a Wordle for lifters.",
  "Powered by caffeine and ego lifting.",
  "Probably easier than Bulgarian split squats.",
  "For people who know what RPE means.",
  "Chest day approved.",
  "Machine stack detectives welcome.",
  "You call that full ROM?",
  "Test your gym IQ.",
  "For hypertrophy scholars.",
  "Built for people who rerack plates.",
  "Today's exercise survived leg day.",
  "Guess harder.",
  "No straps needed.",
  "Warm up your brain before your workout.",
  "Your coach would know this one.",
  "One missed clue away from failure.",
  "Finally, something for gym nerds.",
  "Certified pre-workout activity.",
  "Today's lift is judging you.",
  "Spotter not included.",
  "More addictive than checking your pump.",
  "Do you even know anatomy?",
  "Training to failure starts here.",
  "One exercise. Infinite ego.",
  "Welcome back, bro scientist.",
  "Strength through pattern recognition.",
  "Somewhere, a PT knows the answer.",
  "No pain, no hints.",
  "Built different. Guessed differently.",
  "This one activates the ego.",
  "If you know, you know.",
  "Your split won't save you here.",
  "Daily challenge for gym obsessives.",
  "The daily game for lifters.",
  "Guess the movement. Save the streak.",
  "A tiny game for serious lifters.",
  "Leg day survivors welcome.",
  "Every day a new exercise.",
  "Not your average fitness game.",
  "The exercise guessing game.",
  "Today's gym knowledge test.",
  "Train your knowledge. Every day.",
] as const;

export function getRandomLiftdleSplashline(randomValue = Math.random()) {
  const index = Math.floor(randomValue * LIFTDLE_SPLASHLINES.length);
  return LIFTDLE_SPLASHLINES[index] ?? LIFTDLE_SPLASHLINES[0];
}
